config/routes.rb
VisualCultV2::Application.routes.draw do

  get '/admin' => 'pages#admin'

  match '/vote/:id' => 'jscripts#vote'
  match '/take_role/:user_id/:role_id' => 'jscripts#take_role'

  match '/admin/permissions/roles', :as => :users_roles

  namespace :admin do
    resources :technologies, :colors, :rubriks, :interiors, :permissions, :decors
  end

  devise_for :users

  resources :users do
    resources :galleries do
      resources :photos
    end
  end

  resources :users do
    resources :blogs
  end

  resources :news

  root :to => 'pages#index'

end

app/models/interior.rb
class Interior < ActiveRecord::Base
  attr_accessible :name
end

app/controllers/admin/interiors_controller.rb
class Admin::InteriorsController < ApplicationController
  def index
    @interiors = Interior
  end

  def new
    @interior = Interior.new
  end

 def create
   interior = Interior.new(params[:interior])
   if interior.save
     redirect_to admin_interiors_path
   else
     render :new
   end
 end

  def edit
    @interior = Interior.find(params[:id])
  end

  def update
    interior = Interior.find(params[:id])
    if interior.update_attributes(params[:interior])
      redirect_to admin_interiors_path
    else
      rener :new
    end
  end

  def destroy
    interior = Interior.find(params[:id])
    interior.destroy
    redirect_to admin_interiors_path
  end
end

app/helpers/admin/interiors_helper.rb
module Admin::InteriorsHelper
  def get_interiors
    Interior
  end
end

app/views/admin/interiors/edit.html.erb
<%= content_tag :div, 'Обновить интерьер' %>

<%= form_for @interior, :url => {:action => 'update'} do |f| %>
    <%= f.text_field 'name' %>
    <%=	content_tag :button, t('save') %>
<% end %>

app/views/admin/interiors/index.html.erb
<%= link_to t('add'), new_admin_interior_path %> <br />
<% @interiors.all.each do |interior| %>
    <%= interior.name %>
    <%= link_to t('edit'), edit_admin_interior_path(interior.id) %>
    <%= link_to t('delete'), admin_interior_path(interior.id), :method => :delete%>  <br />
<% end %>

app/views/admin/interiors/new.html.erb
<%= content_tag :div, 'Добавить интерьер' %>

<%= form_for @interior, :url => {:action => 'create'} do |f| %>
    <%= f.text_field 'name' %>
    <%=	content_tag :button, t('save') %>
<% end %>