config/routes.rb
VisualCultV2::Application.routes.draw do

  get '/admin' => 'pages#admin'

  match '/vote/:id' => 'jscripts#vote'
  match '/take_role/:user_id/:role_id' => 'jscripts#take_role'

  match '/admin/permissions/roles', :as => :users_roles

  namespace :admin do
    resources :technologies, :colors, :rubriks, :interiors, :permissions, :decors
  end

  devise_for :users

  resources :users do
    resources :galleries do
      resources :photos
    end
  end

  resources :users do
    resources :blogs
  end

  resources :news

  root :to => 'pages#index'

end

app/models/new.rb
class New < ActiveRecord::Base
  attr_accessible :picture, :text, :title, :tags

  mount_uploader :picture, PictureUploader

  validates :title, :presence => true
  validates :text,  :presence => true
  validates :tags,  :presence => true

end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  #filter_access_to :all

  include ApplicationHelper
  include NewsHelper

  def index
    @news = New.order('created_at DESC').page(params[:page]).per(10)
  end

  def new
    @new = New.new
  end

  def create
    @new = New.new(params[:new])
    if @new.save
      redirect_to news_index_path
    else
      render :new
    end
  end

  def edit
    @new = New.find(params[:id])
  end

  def update
    new = New.find(params[:id])
    if new.update_attributes(params[:new])
      redirect_to news_index_path
    else
      render :edit
    end
  end

  def destroy
    new = New.find(params[:id])
    new.destroy
    redirect_to news_index_path
  end

end

app/helpers/news_helper.rb
module NewsHelper
  def tags_by_new_id(new_id)
    new = New.find(new_id).tags.split(/\s*,\s*/).map(&:to_s).map{ |tag| (link_to tag, '#')  }.join(', ').html_safe
  end

  def active_news?
    'active' if controller_name == 'news'
  end
end

app/views/news/edit.html.erb
<% content_for(:head) do %>
    <script type="text/javascript" >
        $(document).ready(function() {
            $("#markItUp").markItUp(myBbcodeSettings);
        });
    </script>
<% end %>

<div class="container">
<%= form_for @new, :validate => true, :url => {:action => 'update'}, :html => { :multipart => true } do |f| %>
    <div class="row-fluid">
      <div class="span3">
        <%= f.label :picture %>
        <%= f.file_field :picture, :maxlength => 64, :tabindex => 1 %>

        <%= f.label :title %>
        <%= f.text_field :title, :size => 31, :tabindex => 2 %>
        <%= f.label :text %>
        <%= f.text_area :text, :size => '30x10', :tabindex => 3, :id => 'markItUp' %>
        <%= f.label :tags %>
        <%= f.text_area :tags, :size => '113x5', :tabindex => 4 %>
      </div>
    </div>
    <%= content_tag :button, t(:save), :tabindex => 4 %>
<% end %>
</div>

app/views/news/index.html.erb
<div class="container">
  <%=  link_to t('news.add'), new_news_path if permitted_to? [:create, :new], :news  %>
    <ul class="news">
      <% @news.all.each do |new| %>
      <li>
        <div class="news-head">
          <span class="date"><%= new.created_at.strftime('%d.%m.%y, %H:%M') %></span>
          <h2><%= new.title %></h2>
            <%= link_to '', edit_news_path(new.id), :class => 'ico ico-pencil' if can?('edit_news') %>
            <%= link_to '', news_path(new.id), :method => :delete, :class => 'ico ico-close-small', :confirm => t('news.confirm_delete') if can?('delete_news') %>
        </div>
        <div class="news-body">
          <%= image_tag new.picture.url, :class => 'news-image' %>
          <%= raw new.text.bbcode_to_html %>
        </div>
        <div class="tags">
          <strong><%= t('news.tags') %>:</strong> <%= tags_by_new_id(new.id) %>
        </div>
        <%= render 'layouts/social/social_news' %>
      </li>
      <% end %>
    </ul>
    <%= paginate @news %>
</div>

app/views/news/new.html.erb
<% content_for(:head) do %>
    <script type="text/javascript" >
        $(document).ready(function() {
            $("#markItUp").markItUp(myBbcodeSettings);
        });
    </script>
<% end %>

<div class="container">
<%= form_for @new, :validate => true, :url => {:action => 'create'}, :html => { :multipart => true } do |f| %>
    <div class="row-fluid">
      <div class="span3">
        <%= f.label :picture %>
        <%= f.file_field :picture, :maxlength => 64, :tabindex => 1 %>

        <%= f.label :title %>
        <%= f.text_field :title, :size => 31, :tabindex => 2 %>
        <%= f.label :text %>
        <%= f.text_area :text, :size => '30x10', :tabindex => 3, :id => 'markItUp' %>
        <%= f.label :tags %>
        <%= f.text_area :tags, :size => '113x5', :tabindex => 4 %>
      </div>
    </div>
    <%= content_tag :button, t(:save), :tabindex => 4 %>
<% end %>
</div>