config/routes.rb
VisualCultV2::Application.routes.draw do

  get '/admin' => 'pages#admin'

  match '/vote/:id' => 'jscripts#vote'
  match '/take_role/:user_id/:role_id' => 'jscripts#take_role'

  match '/admin/permissions/roles', :as => :users_roles

  namespace :admin do
    resources :technologies, :colors, :rubriks, :interiors, :permissions, :decors
  end

  devise_for :users

  resources :users do
    resources :galleries do
      resources :photos
    end
  end

  resources :users do
    resources :blogs
  end

  resources :news

  root :to => 'pages#index'

end

app/models/rubrik.rb
class Rubrik < ActiveRecord::Base
  attr_accessible :name
end

app/controllers/admin/rubriks_controller.rb
class Admin::RubriksController < ApplicationController
  def index
    @rubriks = Rubrik
  end

  def new
    @rubrik = Rubrik.new
  end

  def create
    rubrik = Rubrik.new(params[:rubrik])
    if rubrik.save
      redirect_to admin_rubriks_path
    else
      render :new
    end
  end

  def edit
    @rubrik = Rubrik.find(params[:id])
  end

  def update
    rubrik = Rubrik.find(params[:id])
    if rubrik.update_attributes(params[:rubrik])
      redirect_to admin_rubriks_path
    else
      render :edit
    end
  end

  def destroy
    rubrik = Rubrik.find(params[:id])
    rubrik.destroy
    redirect_to admin_rubriks_path
  end
end

app/helpers/admin/rubriks_helper.rb
module Admin::RubriksHelper
  def get_rubriks
    rubrik = Rubrik
  end
end

app/views/admin/rubriks/edit.html.erb
<%= content_tag :div, 'Редактировать раздел' %>

<%= form_for @rubrik, :url => {:action => 'update'} do |f| %>
    <%= f.text_field 'name' %>
    <%=	content_tag :button, t('update') %>
<% end %>

app/views/admin/rubriks/index.html.erb
<%= link_to t('add'), new_admin_rubrik_path %> <br />
<% @rubriks.all.each do |rubrik| %>
    <%= rubrik.name %>
    <%= link_to t('edit'), edit_admin_rubrik_path(rubrik.id) %>
    <%= link_to t('delete'), admin_rubrik_path(rubrik.id), :method => :delete%>  <br />
<% end %>

app/views/admin/rubriks/new.html.erb
<%= content_tag :div, 'Добавить рубрику' %>

<%= form_for @rubrik, :url => {:action => 'create'} do |f| %>
    <%= f.text_field 'name' %>
    <%=	content_tag :button, t('save') %>
<% end %>