config/routes.rb
VisualCultV2::Application.routes.draw do

  get '/admin' => 'pages#admin'

  match '/vote/:id' => 'jscripts#vote'
  match '/take_role/:user_id/:role_id' => 'jscripts#take_role'

  match '/admin/permissions/roles', :as => :users_roles

  namespace :admin do
    resources :technologies, :colors, :rubriks, :interiors, :permissions, :decors
  end

  devise_for :users

  resources :users do
    resources :galleries do
      resources :photos
    end
  end

  resources :users do
    resources :blogs
  end

  resources :news

  root :to => 'pages#index'

end

app/models/blog.rb
class Blog < ActiveRecord::Base
  attr_accessible :picture, :text, :title, :tags

  mount_uploader :picture, PictureUploader

  belongs_to :user

  validates :title, :presence => true
  validates :text,  :presence => true
  validates :tags,  :presence => true
end

app/models/color.rb
class Color < ActiveRecord::Base
  attr_accessible :name

  validates :name, :uniqueness => true
end

app/models/decor.rb
class Decor < ActiveRecord::Base
  attr_accessible :name
end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  attr_accessible :name, :description

  has_many :photos
  belongs_to :user

  validates :name, :presence => true

  scope :gallery_by_user_id, lambda {|user_id| where('user_id = ?',user_id)}
end

app/models/interior.rb
class Interior < ActiveRecord::Base
  attr_accessible :name
end

app/models/new.rb
class New < ActiveRecord::Base
  attr_accessible :picture, :text, :title, :tags

  mount_uploader :picture, PictureUploader

  validates :title, :presence => true
  validates :text,  :presence => true
  validates :tags,  :presence => true

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  attr_accessible :name, :price, :sell, :src_preview, :miniature_one, :miniature_two, :date_create, :city, :description,
                  :width, :height, :color_one_id, :color_two_id, :rubrik_one_id, :rubrik_two_id, :tags, :size_one, :size_two,
                  :size_three, :price_one, :price_two, :price_three, :decor_one_id, :decor_two_id, :decor_three_id,
                  :edition_one, :edition_two, :edition_three, :technology_id, :raiting

  mount_uploader :src_preview, SrcPreviewUploader
  mount_uploader :miniature_one, MiniatureOneUploader
  mount_uploader :miniature_two, MiniatureTwoUploader

  belongs_to :gallery
end

app/models/role.rb
class Role < ActiveRecord::Base
  attr_accessible :name
  has_and_belongs_to_many :users

  validates :name, :uniqueness => true
end

app/models/rubrik.rb
class Rubrik < ActiveRecord::Base
  attr_accessible :name
end

app/models/technology.rb
class Technology < ActiveRecord::Base
  attr_accessible :name
end

app/models/user.rb
# coding: utf-8

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me,
                  :second_name, :name, :phone, :login, :birthday, :city, :about, :what_inspires, :avatar
  # attr_accessible :title, :body

  has_many :blogs
  has_many :galleries
  has_and_belongs_to_many :roles

  mount_uploader :avatar, AvatarUploader

  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  phone_regex = /^[0-9\-\s]+$/
  name_regex = /^[a-zA-Zа-яА-Я\-]{2,40}$/


  validates :login, :presence => true,
            :length => {:maximum => 50},
            :uniqueness => { :case_sensitive => false }


  validates :email, :presence   => true,
            :format             => { :with => email_regex },
            :uniqueness         => true

  validates :password, :presence => true,
            :confirmation        => true,
            :length              => { :within => 6..40}

  validates :phone, :presence => true,
            :format           => { :with => phone_regex },
            :length           => { :within => 5..40},
            :uniqueness       => true

  validates :name, :presence => true,
            :format          => { :with => name_regex },
            :length          => { :within => 2..40}

  validates :second_name, :presence => true,
            :format                 => { :with => name_regex },
            :length                 => { :within => 2..40}

  before_create :add_default_role

  def role_symbols
    (roles || []).map {|r| r.name.to_sym}
  end

  private
  def add_default_role
    self.roles<<Role.find(3)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def logo
    image_tag("i/logo.png", :alt => "Begovel")
  end

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  def can?(*permission_name)
    current_user && permission_name.inject(false) { |acc, pn| acc || current_user.can?(pn) }
  end

  def have_permissions_controller(user_id)
    action_name_helper = action_name
    action_name_helper = 'create' if action_name == 'new'
    action_name_helper = 'update' if action_name == 'edit'

    current_permission  = action_name_helper + '_' + controller_name

    if (current_user && can?(current_permission) && current_user.id == user_id) || (current_user && can?('moderate_' + controller_name))
      permissions = true
    else
      permissions = false
    end
  end

  def top_menu
    if ['galleries', 'photos'].include?(controller_name)
      render 'layouts/menus/auth_top_menu'
    elsif controller_name == 'users' && action_name != 'index'
      render 'layouts/menus/auth_top_menu'
    else
      render 'layouts/menus/top_menu'
    end
  end

  def get_filter
    unless ['users', 'galleries'].include?(controller_name)
      render 'layouts/menus/filter'
    end
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def tags_by_blog_id(new_id)
    new = Blog.find(new_id).tags.split(/\s*,\s*/).map(&:to_s).map{ |tag| (link_to tag, '#')  }.join(', ').html_safe
  end
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/jscripts_helper.rb
module JscriptsHelper
end

app/helpers/news_helper.rb
module NewsHelper
  def tags_by_new_id(new_id)
    new = New.find(new_id).tags.split(/\s*,\s*/).map(&:to_s).map{ |tag| (link_to tag, '#')  }.join(', ').html_safe
  end

  def active_news?
    'active' if controller_name == 'news'
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
  def gallery(gallery_id, gallery_name, user_id)
    if gallery_name != ''
      gallery = User.find(user_id).galleries.find_by_name(gallery_name)
      if gallery.nil?
        gallery = User.find(user_id).galleries.create(:name => gallery_name)
      end
    else
      gallery = User.find(user_id).galleries.find(gallery_id) unless gallery_id.nil?
    end
  end

  def str_to_links(str)
    str.split(/\s*,\s*/).map(&:to_s).map{ |tag| (link_to tag, '#')  }.join(', ').html_safe
  end

  def date_to_db_format(year)
    Date.civil(year.to_i).to_formatted_s(:db)
  end

  def get_rubriks_and_tech(*obj)
    # :TODO Доделать для фотографии show раздел и техники

    # :TODO Сделать photo->raiting default => 0

    # :TODO Спросить о модерации
    # :TODO Сделать меню
  end
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def user_avatar(user)
    if File.exists?(user.avatar.url.to_s)
      user.avatar.url
    else
      'placeholder/placeholder.jpg'
    end
  end
end

app/views/layouts/_auth.html.erb
<div class="pane">
  <% unless user_signed_in? %>
  <ul class="auth">
    <li class="first">
      <a href="#auth" onClick="expandit('auth_popup')"><%= t :login_in %></a>
    </li>
    <li>
      <%= link_to t(:sign_up), new_user_registration_path %>
    </li>
  </ul>

  <form action="/search.php" method="post" class="search">
    <input type="submit" class="submit" text="search" />
    <input type="text" class="text" placeholder="Поиск" />
  </form>

  <div id="auth_popup" class="popup" style="display:none">
    <a class="close" href="#close_window" onClick="expandit('auth_popup')"><i class="ico ico-close">&nbsp;</i></a>
    <%= render 'devise/sessions/new' %>
  </div>

  <% else %>

    <ul class="auth">
        <li class="first">
            <a href="#username" onClick="expandit('profile-link')"><%= current_user.login %>&#9660;</a>
            <ul id="profile-link" class="popup" style="display:none">
              <% if current_user.roles.exists?(Role.find_by_name('Admin')) %>
                <li><%= link_to t('admin.admin_page'), admin_path %></li>
              <% else %>
                <li><a href="#">Добавить работу</a></li>
                <li><a href="<%= user_path(current_user.id) %>">Личный кабинет</a></li>
                <li><a href="<%= new_user_gallery_path(current_user.id) %>">Создать галлерею</a></li>
                <li><%= link_to 'Редактировать профиль', edit_user_registration_path %></li>
              <% end %>
            </ul>
        </li><li>
        <%= link_to t(:sign_out), destroy_user_session_path, :method => :delete %>
        </li>
    </ul>

    <form action="/search.php" method="post" class="search">
      <input type="submit" class="submit" text="search" />
      <input type="text" class="text" placeholder="Поиск" />
    </form>

    <a class="basket" href="#"><i class="ico ico-basket"></i>2</a>

  <% end %>

</div>

app/views/layouts/_footer.html.erb
<div id="footer">
  <div class="container">
    <div class="links">
      <span class="label">Контакты:</span>
      <ul>
        <li class="fb">
          <a href="http://www.facebook.com">facebook</a>
        </li><li class="vk">
        <a href="http://vk.com">vkontakte</a>
      </li><li class="em">
        <a href="mailto:blabla@blacksheep.ru">mailto:blacksheep</a>
      </li><li class="sk">
        <a href="skype.com">skype.com</a>
      </li><li class="tw">
        <a href="http://twitter.com">twitter</a>
      </li>
      </ul>
    </div>
    <p class="copyright">2013. Black sheep</p>
  </div>
</div>

app/views/layouts/_head.html.erb
<div id="header">
  <h1><%= link_to logo, root_path %></h1>
  <%= render 'layouts/auth' %>
  <%= top_menu %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VisualCult</title>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <!-- meta http-equiv='X-UA-Compatible' content='IE=7' / -->

  <%#= favicon_link_tag 'favicon.ico', :rel => 'icon', :type => 'image/x-icon' %>
  <%#= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon', :type => 'image/x-icon' %>

  <%= stylesheet_link_tag 'application'%>

  <!--[if IE]>
  <%= stylesheet_link_tag 'default.ie' %>
  <![if lte IE 8]>
			<%= stylesheet_link_tag 'default.ie8' %>
		<![endif]>
		<![if lte IE 7]>
			<%= stylesheet_link_tag 'default.ie7' %>
		<![endif]>
		<![if lte IE 6]>
			<%= stylesheet_link_tag 'default.ie6' %>
		<![endif]>
	<![endif]-->


  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'http://fonts.googleapis.com/css?family=PT+Sans' %>

  <%= yield :head %>
</head>
<body>
<div id="cont">
  <%= render 'layouts/head' %>
  <div id="main-content">
    <%= get_filter %>
    <%= yield %>
  </div>
  <div id="footer-spacer"></div>
</div>
<%= render 'layouts/footer' %>
<%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/layouts/menus/_auth_top_menu.html.erb
<ul class="nav author-nav">
  <li class="author-name">
    <span><%= @user.name %> <%= @user.second_name %></span>
    <a class="add-favorite" href="#1">Добавить в избранное</a>
  </li>
  <li>
    <%= link_to 'Работы', root_path %>
    <ul>
      <li>
        <%= link_to 'Серия и описания', user_galleries_path(@user.id) %>
      </li>
      <li>
        <a href="#2">Список серий</a>
      </li>
      <li>
        <a href="#3">Без серий</a>
      </li>
    </ul>
  </li>
  <li>
    <%= link_to 'Об авторе', user_path(@user.id) %>
    <ul>
      <li>
        <a href="#1">Статистика автора</a>
      </li>
    </ul>
  </li>
</ul>

<% # :TODO не забыть о class="active" у меню %>

app/views/layouts/menus/_filter.html.erb
<div id="sidebar">
  <ul>
    <li>
      <a href="javascript:void(0)" onclick="openMenu('tech'); return false">Техника</a>
      <div id="tech" class="defmenu">
        <ul>
        <% get_technologies.all.each do |tech| %>
            <li><%= tech.name %></li>
        <% end %>
        </ul>
      </div>
    </li>
    <li>
      <a href="javascript:void(0)" onclick="openMenu('rubrik')">Раздел</a>
      <div id="rubrik" class="defmenu">
        <ul>
          <% get_rubriks.all.each do |rubrik| %>
            <li><%= rubrik.name %></li>
          <% end %>
        </ul>
      </div>
    </li>
    <li>
      <%= link_to 'Авторы', users_path %>
    </li>
    <li>
      <a href="#4">Подборка</a>
    </li>
    <li>
      <a href="#5">Ширина</a>
    </li>
    <li>
      <a href="#6">Формат</a>
    </li>
    <li>
      <a href="javascript:void(0)" onclick="openMenu('interior')">Интерьер</a>
      <div id="interior" class="defmenu">
        <ul>
            <% get_interiors.all.each do |interior| %>
                <li><%= interior.name %></li>
            <% end %>
        </ul>
      </div>
    </li>
    <li>
      <a href="javascript:void(0)" onclick="openMenu('color'); return false">Цвет</a>
      <div id="color" class="defmenu">
        <ul>
        <% get_colors.all.each do |color| %>
        <li><%= color.name %></li>
        <% end %>
        </ul>
      </div>
    </li>
    <li>
      <a href="#10">Цена</a>
    </li>
    <li>
      <a href="#11">Сортировка</a>
    </li>
  </ul>
</div>

app/views/layouts/menus/_top_menu.html.erb
<ul class="nav">
  <li class>
    <a >Магазин</a>
    <ul>
      <li class>
        <a href="#2">Акции</a>
      </li>
      <li class>
        <a href="#3">Карзина</a>
      </li>
    </ul>
  </li>

  <li class>
    <%= link_to t('news.news'), news_index_path, :class => active_news? %>
  </li>

  <li class>
    <a href="#3">О проекте</a>
    <ul>
      <li>

      </li>
      <li>

      </li>
      <li>

      </li>
      <li>

      </li>
    </ul>
  </li>
</ul>

app/views/layouts/social/_social_auth_info.html.erb
<div class="links pull-right">
  <ul>
    <li class="fb">
      <a href="http://www.facebook.com">facebook</a>
    </li>
    <li class="vk">
      <a href="http://vk.com">vkontakte</a>
    </li>
    <li class="gp">
      <a href="http://plus.google.com">google+</a>
    </li>
    <li class="ok">
      <a href="http://odnoklassniki.ru">odnoklassniki</a>
    </li>
    <li class="pin">
      <a href="#">odnoklassniki</a>
    </li>
    <li class="tw">
      <a href="http://twitter.com">twitter</a>
    </li>
  </ul>
</div>

app/views/layouts/social/_social_news.html.erb
<div class="links pull-right">
  <ul>
    <li class="fb">
      <a href="http://www.facebook.com">facebook</a>
    </li>
    <li class="vk">
      <a href="http://vk.com">vkontakte</a>
    </li>
    <li class="gp">
      <a href="http://plus.google.com">google+</a>
    </li>
    <li class="ok">
      <a href="http://odnoklassniki.ru">odnoklassniki</a>
    </li>
    <li class="pin">
      <a href="#">odnoklassniki</a>
    </li>
    <li class="tw">
      <a href="http://twitter.com">twitter</a>
    </li>
  </ul>
</div>

app/views/layouts/social/_social_photo.html.erb
<div class="links">
  <span class="label">Без регистрации Вы можете поделиться ссылкой на работу с друзьями:</span>
  <ul>
    <li class="fb">
      <a href="http://www.facebook.com">facebook</a>
    </li>
    <li class="vk">
      <a href="http://vk.com">vkontakte</a>
    </li>
    <li class="gp">
      <a href="http://plus.google.com">google+</a>
    </li>
    <li class="ok">
      <a href="http://odnoklassniki.ru">odnoklassniki</a>
    </li>
    <li class="pin">
      <a href="#">odnoklassniki</a>
    </li>
    <li class="tw">
      <a href="http://twitter.com">twitter</a>
    </li>
  </ul>
</div>

app/views/layouts/social/_social_photo_under_photo.html.erb
<div class="links pull-right">
<span class="label">Рассказать друзьям:</span>
<ul>
  <li class="fb">
    <a href="http://www.facebook.com">facebook</a>
  </li>
  <li class="vk">
    <a href="http://vk.com">vkontakte</a>
  </li>
  <li class="gp">
    <a href="http://plus.google.com">google+</a>
  </li>
  <li class="ok">
    <a href="http://odnoklassniki.ru">odnoklassniki</a>
  </li>
  <li class="pin">
    <a href="#">odnoklassniki</a>
  </li>
  <li class="tw">
    <a href="http://twitter.com">twitter</a>
  </li>
</ul>
</div>

app/views/layouts/social/_social_photo_void.html.erb
<span class="tooltip tooltip-right" id="tooltip-rating" style="display:none">
    <p>Чтобы голосовать за работу, необходимо <strong>зарегистрироваться</strong></p>
    <div class="links">
      <span class="label">Без регистрации Вы можете поделиться ссылкой:</span>
      <ul>
        <li class="fb">
          <a href="http://www.facebook.com">facebook</a>
        </li>
        <li class="vk">
          <a href="http://vk.com">vkontakte</a>
        </li>
        <li class="gp">
          <a href="http://plus.google.com">google+</a>
        </li>
        <li class="ok">
          <a href="http://odnoklassniki.ru">odnoklassniki</a>
        </li>
        <li class="pin">
          <a href="#">odnoklassniki</a>
        </li>
        <li class="tw">
          <a href="http://twitter.com">twitter</a>
        </li>
      </ul>
    </div>
</span>